version: 2.1
jobs:
   DeployDevelop:
     docker:
       - image: circleci/python:3

     environment:
       GITHUB_TOKEN: "17e396315d1e9961cbaa46afd2f100257990555"
     steps:
       - checkout
       - run: echo "start prepare envirement..."
       - run:
           name: prepareEnv
           command: |
             echo $GITHUB_TOKEN
             export GITHUB_TOKEN=${GITHUB_TOKEN}"7"
             sudo apt update
             curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
             sudo apt install nodejs
             node --version
             npm --version
             cd bookStore
             ls
             npx semantic-release --debug
             echo ${GITHUB_TOKEN}
             appVersion=$(cat ./package.json | jq -r '.version')
             echo ${appVersion}

   approval:
     docker:
       - image: circleci/python:3
     steps:
       - run: echo "You wanna destroy it?"
   destroy:
     docker:
       - image: circleci/python:3
     steps:
       - checkout
       - attach_workspace:
           at: /tmp/workspace
       - run: cat /tmp/workspace/artifects/output.status
       - run:
           name: destroy
           command: |
             sudo apt update
             sudo apt install -y python3-pip jq
             sudo pip3 install awscli
             echo ${AWS_ACCESS_KEY_ID}
             echo ${AWS_SECRET_ACCESS_KEY}

             bash ./manage_vpc.sh destroy

workflows:
   DeployDevelop123:
     jobs:
       - DeployDevelop:
           name: DeployDevelop

