version: 2.1
jobs:
   DeployDevelop:
     docker:
       - image: circleci/python:3

     environment:
       REPO_ENC_KEY: 4826F5CA0F50D4EA265D5691C18B5691776ED1FB10C5DF73CE45614AF12AE0E1
       REPO_ENC_IV: 8BD9321FB88376E7944339FAA16A26C0
     steps:
       - checkout
       - run: echo "start prepare envirement..."
       - run:
           name: prepareEnv
           command: |
             openssl aes-256-cbc -d -K $REPO_ENC_KEY -iv $REPO_ENC_IV -in git_deploy_key.enc -out /tmp/git_deploy_key
             chmod 600 /tmp/git_deploy_key
             cat /tmp/git_deploy_key
             cp config ~/.ssh/
             ls -alt ~/.ssh/
             echo 'echo ${SSL_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
             eval "$(ssh-agent -s)"
             openssl aes-256-cbc -d -K $REPO_ENC_KEY -iv $REPO_ENC_IV -in git_deploy_key.enc -out /tmp/git_deploy_key
             sudo apt update
             curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
             sudo apt install nodejs
             node --version
             npm --version
             cd bookStore
             npx semantic-release
             appVersion=$(cat ./package.json | jq -r '.version')
             echo ${appVersion}


   approval:
     docker:
       - image: circleci/python:3
     steps:
       - run: echo "You wanna destroy it?"
   destroy:
     docker:
       - image: circleci/python:3
     steps:
       - checkout
       - attach_workspace:
           at: /tmp/workspace
       - run: cat /tmp/workspace/artifects/output.status
       - run:
           name: destroy
           command: |
             sudo apt update
             sudo apt install -y python3-pip jq
             sudo pip3 install awscli
             echo ${AWS_ACCESS_KEY_ID}
             echo ${AWS_SECRET_ACCESS_KEY}

             bash ./manage_vpc.sh destroy

workflows:
   DeployDevelop123:
     jobs:
       - DeployDevelop:
           name: DeployDevelop

